export interface LiberalCourse {
  code: string;
  title: string;
  level: "lower" | "upper";
}

export const LIBERAL_COURSES: LiberalCourse[] = [
  // ============================================================
  // TABLE A - LOWER LEVEL LIBERAL STUDIES
  // ============================================================
  { code: "AER150", title: "Aerospace History", level: "lower" },
  { code: "ANT100", title: "Introduction to Anthropology", level: "lower" },
  { code: "ARB101", title: "Introductory Arabic I", level: "lower" },
  { code: "ARB201", title: "Introductory Arabic II", level: "lower" },
  { code: "ASC120", title: "Introduction to Architecture", level: "lower" },
  { code: "ASC121", title: "Sustainable Architecture", level: "lower" },
  { code: "ASL101", title: "Introductory American Sign Language I", level: "lower" },
  { code: "ASL201", title: "Introductory American Sign Language II", level: "lower" },
  { code: "BLG181", title: "Biology of a Living City", level: "lower" },
  { code: "BMS150", title: "Introduction to the Human Genome", level: "lower" },
  { code: "BPM406", title: "Chinese Instrumental Music", level: "lower" },
  { code: "BPM441", title: "Music of India", level: "lower" },
  { code: "BPM474", title: "Gospel Music: Songs for the Spirit", level: "lower" },
  { code: "BPM484", title: "Music of the African Diaspora", level: "lower" },
  { code: "CHN101", title: "Introductory Chinese I", level: "lower" },
  { code: "CHN201", title: "Introductory Chinese II", level: "lower" },
  { code: "CHY182", title: "Chemistry Applications to Living Systems", level: "lower" },
  { code: "CHY183", title: "Introduction to Forensic Sciences", level: "lower" },
  { code: "CMN230", title: "Trans Studies and Communication", level: "lower" },
  { code: "CMN231", title: "Communicating with Comics", level: "lower" },
  { code: "CRB100", title: "Introduction to the Caribbean", level: "lower" },
  { code: "CRM101", title: "Understanding Crime in Canadian Society", level: "lower" },
  { code: "DST300", title: "Whose Lives Matter?", level: "lower" },
  { code: "ECN110", title: "The Economy and Society", level: "lower" },
  { code: "ECN205", title: "Economics of Change and Conflict", level: "lower" },
  { code: "ECN210", title: "Understanding Economics", level: "lower" },
  { code: "ECN340", title: "The Economics of Human Behaviour", level: "lower" },
  { code: "ECN440", title: "Economic Issues in Financial Markets", level: "lower" },
  { code: "ENG101", title: "Laughter and Tears: Comedy and Tragedy", level: "lower" },
  { code: "ENG104", title: "The Short Story", level: "lower" },
  { code: "ENG112", title: "Zap, Pow, Bang: Pop Lit", level: "lower" },
  { code: "ENG201", title: "Myth and Literature", level: "lower" },
  { code: "ENG203", title: "The Literature of Indigenous Peoples", level: "lower" },
  { code: "ENG212", title: "Cultures in Crisis", level: "lower" },
  { code: "EUS180", title: "Global Water Issues", level: "lower" },
  { code: "FNU100", title: "Canadian Cuisine: Historical Roots", level: "lower" },
  { code: "FNU101", title: "Food Practices and Policy", level: "lower" },
  { code: "FRE101", title: "Introductory French I", level: "lower" },
  { code: "FRE201", title: "Introductory French II", level: "lower" },
  { code: "FRS102", title: "Francophone Detective Fiction", level: "lower" },
  { code: "GEO106", title: "Geographies of Everyday Life", level: "lower" },
  { code: "GEO108", title: "Geography of the Global Village", level: "lower" },
  { code: "GEO110", title: "The Physical Environment", level: "lower" },
  { code: "GEO206", title: "Regions, Nations and the Global Community", level: "lower" },
  { code: "GEO208", title: "Geography of the Global Economy", level: "lower" },
  { code: "GEO210", title: "Geography of Hazards", level: "lower" },
  { code: "GEO312", title: "Viva Las Vegas!", level: "lower" },
  { code: "GEO322", title: "A Critical Geography of South Asia", level: "lower" },
  { code: "GRK100", title: "Introduction to Attic Greek", level: "lower" },
  { code: "GRK200", title: "Athens through Comic Poet's Eyes", level: "lower" },
  { code: "HAU100", title: "Haudenosaunee Cultural Perspective", level: "lower" },
  { code: "HST110", title: "U.S. History: Colonial Era to 1877", level: "lower" },
  { code: "HST111", title: "World Turned Upside Down: Europe 1350-1789", level: "lower" },
  { code: "HST112", title: "East Meets West: Asia in the World", level: "lower" },
  { code: "HST118", title: "The City in History", level: "lower" },
  { code: "HST119", title: "Rise of Empires: History Through Film", level: "lower" },
  { code: "HST207", title: "Introduction to Ancient Greece and Rome", level: "lower" },
  { code: "HST210", title: "U.S. History: 1877 to the Present", level: "lower" },
  { code: "HST211", title: "Century of Revolution: Europe 1789-1914", level: "lower" },
  { code: "HST219", title: "Decolonization: History Through Film", level: "lower" },
  { code: "HST222", title: "The History of The Caribbean", level: "lower" },
  { code: "HST307", title: "Canada to 1885: The Founding Societies", level: "lower" },
  { code: "HST325", title: "History of Science and Technology I", level: "lower" },
  { code: "HST375", title: "LGBTQ2S+ Histories", level: "lower" },
  { code: "HST407", title: "Canada from 1885: The Struggle for Identity", level: "lower" },
  { code: "HST425", title: "History of Science and Technology II", level: "lower" },
  { code: "HST426", title: "Major Themes in International Relations", level: "lower" },
  { code: "HST430", title: "Food History", level: "lower" },
  { code: "HST488", title: "Britain since 1815", level: "lower" },
  { code: "IRL100", title: "Intro to World Art I: Pictorial Arts", level: "lower" },
  { code: "IRL200", title: "Introduction to World Textile History", level: "lower" },
  { code: "LAT100", title: "Introduction to Latin", level: "lower" },
  { code: "LAT200", title: "Latin and the Roman World", level: "lower" },
  { code: "LIR205", title: "Greek and Latin Keys to Academic English", level: "lower" },
  { code: "LNG111", title: "Language and Identity", level: "lower" },
  { code: "LNG112", title: "Spoken and Written Language", level: "lower" },
  { code: "LNG113", title: "Language and Public Life", level: "lower" },
  { code: "LNG121", title: "Language and Society", level: "lower" },
  { code: "MEC110", title: "Energy and the Environment", level: "lower" },
  { code: "MHK101", title: "Introductory Kanyen'kéha I", level: "lower" },
  { code: "MHK201", title: "Introductory Kanyen'kéha II", level: "lower" },
  { code: "MUS101", title: "Intro to World and Early European Music", level: "lower" },
  { code: "MUS105", title: "Voices Without Borders: Global Chorus", level: "lower" },
  { code: "MUS106", title: "The Architecture of Music", level: "lower" },
  { code: "MUS201", title: "Introduction to Classical Music", level: "lower" },
  { code: "MUS220", title: "Global Popular Music", level: "lower" },
  { code: "NMA120", title: "Video Games and Culture", level: "lower" },
  { code: "NPF188", title: "From Page to Screen", level: "lower" },
  { code: "PCS111", title: "Physics in the News", level: "lower" },
  { code: "PCS181", title: "Introduction to Astronomy", level: "lower" },
  { code: "PCS182", title: "Life in the Milky Way Galaxy", level: "lower" },
  { code: "PHL101", title: "Plato and the Roots of Western Philosophy", level: "lower" },
  { code: "PHL110", title: "Philosophy of Religion I", level: "lower" },
  { code: "PHL187", title: "Classical Philosophy", level: "lower" },
  { code: "PHL201", title: "Problems in Philosophy", level: "lower" },
  { code: "PHL202", title: "Philosophy of Technology", level: "lower" },
  { code: "PHL210", title: "Introduction to Indian Philosophy", level: "lower" },
  { code: "PHL214", title: "Critical Thinking", level: "lower" },
  { code: "PHL306", title: "Freedom, Equality, Limits of Authority", level: "lower" },
  { code: "PHL333", title: "Philosophy of Human Nature", level: "lower" },
  { code: "PHL365", title: "Philosophy of Beauty", level: "lower" },
  { code: "PHL366", title: "Existentialism and Art and Culture", level: "lower" },
  { code: "PHL406", title: "Issues of Life, Death and Poverty", level: "lower" },
  { code: "POH105", title: "Ounce of Prevention: Public Health Past", level: "lower" },
  { code: "POL106", title: "The Politics of Human Needs", level: "lower" },
  { code: "POL128", title: "Politics and Film", level: "lower" },
  { code: "POL129", title: "Immigration and Settlement in Canada", level: "lower" },
  { code: "POL203", title: "Politics of the Environment", level: "lower" },
  { code: "POL208", title: "Globalization and World Politics", level: "lower" },
  { code: "PSY105", title: "Perspectives in Psychology", level: "lower" },
  { code: "PSY304", title: "Psychology of Gender", level: "lower" },
  { code: "PSY308", title: "Psychology of Thinking", level: "lower" },
  { code: "REL100", title: "Introduction to Religious Studies", level: "lower" },
  { code: "REL101", title: "Introduction to World Religions", level: "lower" },
  { code: "REL200", title: "Introduction to Hinduism and Buddhism", level: "lower" },
  { code: "REL205", title: "Introduction to Sikhism", level: "lower" },
  { code: "REL210", title: "Introduction to Chinese Religions", level: "lower" },
  { code: "REL215", title: "Introduction to Judaism", level: "lower" },
  { code: "REL220", title: "Introduction to Christianity", level: "lower" },
  { code: "REL225", title: "Introduction to Islam", level: "lower" },
  { code: "RMG210", title: "Shopping and Society", level: "lower" },
  { code: "RTA180", title: "Music and Film", level: "lower" },
  { code: "SEM101", title: "Sign, Sense and Meaning", level: "lower" },
  { code: "SOC102", title: "Human Origins", level: "lower" },
  { code: "SOC103", title: "How Society Works", level: "lower" },
  { code: "SOC108", title: "Indigenous Peoples and Decolonization", level: "lower" },
  { code: "SOC202", title: "Popular Culture", level: "lower" },
  { code: "SOC203", title: "Social Class and Inequality", level: "lower" },
  { code: "SOC221", title: "The Hip Hop Lens of Society", level: "lower" },
  { code: "SOC305", title: "Sociology of Deviance", level: "lower" },
  { code: "SPN101", title: "Introductory Spanish I", level: "lower" },
  { code: "SPN201", title: "Introductory Spanish II", level: "lower" },
  { code: "THL100", title: "Theatre and the Canadian Identity", level: "lower" },

  // ============================================================
  // TABLE B - UPPER LEVEL LIBERAL STUDIES
  // ============================================================
  { code: "ANT306", title: "Introduction to Linguistic Anthropology", level: "upper" },
  { code: "ARB300", title: "Principles in Arabic Writing", level: "upper" },
  { code: "ARB301", title: "Intermediate Arabic I", level: "upper" },
  { code: "ARB401", title: "Intermediate Arabic II", level: "upper" },
  { code: "ARB501", title: "Advanced Arabic I", level: "upper" },
  { code: "ARB601", title: "Advanced Arabic II", level: "upper" },
  { code: "ASL301", title: "Intermediate American Sign Language I", level: "upper" },
  { code: "ASL401", title: "Intermediate American Sign Language II", level: "upper" },
  { code: "ASL501", title: "Advanced American Sign Language I", level: "upper" },
  { code: "ASL601", title: "Advanced American Sign Language II", level: "upper" },
  { code: "BLG599", title: "Biology Facts in Pop Media Sci-Fiction", level: "upper" },
  { code: "BLG655", title: "Viruses Among Us", level: "upper" },
  { code: "BLG699", title: "Social Factors in Drug Development", level: "upper" },
  { code: "BLG850", title: "What is Cancer?", level: "upper" },
  { code: "BPM530", title: "The Music of East Asia", level: "upper" },
  { code: "CHN301", title: "Intermediate Chinese I", level: "upper" },
  { code: "CHN401", title: "Intermediate Chinese II", level: "upper" },
  { code: "CHN501", title: "Advanced Chinese I", level: "upper" },
  { code: "CHN601", title: "Advanced Chinese II", level: "upper" },
  { code: "CHN612", title: "Contemporary Chinese Language and Culture", level: "upper" },
  { code: "CHS503", title: "Chinese Literary Traditions", level: "upper" },
  { code: "CHS504", title: "Chinese Cultural Traditions", level: "upper" },
  { code: "CHY583", title: "Alternative Energies", level: "upper" },
  { code: "CHY599", title: "The Business of Chemistry and Biology", level: "upper" },
  { code: "CLD500", title: "A Caring World for Children", level: "upper" },
  { code: "CMN601", title: "Visual Communication: A Critical Approach", level: "upper" },
  { code: "CPS650", title: "Computational Thinking in Our World", level: "upper" },
  { code: "CRB500", title: "Families in the Caribbean", level: "upper" },
  { code: "CRB501", title: "Racism and Caribbean Peoples in Canada", level: "upper" },
  { code: "CRB502", title: "Cultural Traditions in the Caribbean", level: "upper" },
  { code: "CRM500", title: "Drug Criminalization and Control", level: "upper" },
  { code: "CRM515", title: "Gendering Justice", level: "upper" },
  { code: "CRM601", title: "Violence in Society", level: "upper" },
  { code: "CYC500", title: "Youth Living on the Edge", level: "upper" },
  { code: "DST500", title: "A History of Madness", level: "upper" },
  { code: "DST508", title: "Cripping the Arts in Canada", level: "upper" },
  { code: "DST510", title: "Death and Everyday Life", level: "upper" },
  { code: "DST601", title: "Mad Poetics", level: "upper" },
  { code: "DST605", title: "Sexuality, Desire and Disability", level: "upper" },
  { code: "ECN503", title: "Economic Development", level: "upper" },
  { code: "ECN505", title: "Economic Issues in Labour Markets", level: "upper" },
  { code: "ECN507", title: "Ethics and Justice in Economics", level: "upper" },
  { code: "ECN509", title: "Economic Issues in Money and Banking", level: "upper" },
  { code: "ECN511", title: "Economy and Environment", level: "upper" },
  { code: "ECN512", title: "The Economics of Sex", level: "upper" },
  { code: "ECN603", title: "Economic Issues in Globalization", level: "upper" },
  { code: "ECN607", title: "Issues in the International Economy", level: "upper" },
  { code: "ECN722", title: "Economic Issues in Professional Sports", level: "upper" },
  { code: "ECN802", title: "The Economies of East Asia", level: "upper" },
  { code: "ELE900", title: "AI: A Socio-Technical Perspective", level: "upper" },
  { code: "ENG503", title: "Science Fiction", level: "upper" },
  { code: "ENG505", title: "Creative Writing", level: "upper" },
  { code: "ENG510", title: "Gothic Horror", level: "upper" },
  { code: "ENG511", title: "The Art of Writing Life", level: "upper" },
  { code: "ENG515", title: "Madness in Fiction", level: "upper" },
  { code: "ENG522", title: "Crime Fiction", level: "upper" },
  { code: "ENG527", title: "Digital Media and Story", level: "upper" },
  { code: "ENG602", title: "Women's Writing", level: "upper" },
  { code: "ENG610", title: "The Language of Love, Sex and Gender", level: "upper" },
  { code: "ENG620", title: "Literatures of the Caribbean", level: "upper" },
  { code: "ENG647", title: "Afrofuturism: Black 2 the Future", level: "upper" },
  { code: "FNF520", title: "Contemporary Family Relations", level: "upper" },
  { code: "FRE301", title: "Intermediate French I", level: "upper" },
  { code: "FRE401", title: "Intermediate French II", level: "upper" },
  { code: "FRE501", title: "Speaking and Writing French I", level: "upper" },
  { code: "FRE503", title: "Middle Ages to Classicism", level: "upper" },
  { code: "FRE505", title: "French Language and Culture", level: "upper" },
  { code: "FRE507", title: "English-French Translation I", level: "upper" },
  { code: "FRE508", title: "Intro to 20th C French Literature I", level: "upper" },
  { code: "FRE509", title: "Franco-Canadian Literature I", level: "upper" },
  { code: "FRE510", title: "Effective Writing", level: "upper" },
  { code: "FRE516", title: "Politics and Play in French Poetry", level: "upper" },
  { code: "FRE601", title: "Speaking and Writing French II", level: "upper" },
  { code: "FRE603", title: "Enlightenment to La Belle Époque", level: "upper" },
  { code: "FRE605", title: "Francophone Language and Culture", level: "upper" },
  { code: "FRE607", title: "English-French Translation II", level: "upper" },
  { code: "FRE608", title: "Intro to 20th C French Literature II", level: "upper" },
  { code: "FRE609", title: "Franco-Canadian Literature II", level: "upper" },
  { code: "FRE610", title: "Cultural Context of Writing", level: "upper" },
  { code: "FRE701", title: "French for Today", level: "upper" },
  { code: "FRE703", title: "French Theatre: Classicism to Romanticism", level: "upper" },
  { code: "FRE704", title: "Intro to Franco-Canadian Culture I", level: "upper" },
  { code: "FRE706", title: "The Life and Times of the French Language", level: "upper" },
  { code: "FRE707", title: "Introduction to French-English Translation", level: "upper" },
  { code: "FRE709", title: "Children's Literature in French", level: "upper" },
  { code: "FRE801", title: "French and New Media", level: "upper" },
  { code: "FRE803", title: "French Theatre: 20th C and Contemporary", level: "upper" },
  { code: "FRE804", title: "Intro to Franco-Canadian Culture II", level: "upper" },
  { code: "FRE901", title: "Francophone Women Writers", level: "upper" },
  { code: "FRE902", title: "Gender and Decadence 1850-1920", level: "upper" },
  { code: "FRE903", title: "The Francophone Short Story", level: "upper" },
  { code: "FRS501", title: "Women and the Arts in 19th Century France", level: "upper" },
  { code: "FRS502", title: "Feminism and French Literature", level: "upper" },
  { code: "FRS602", title: "French Caribbean Literature and Culture", level: "upper" },
  { code: "FRS606", title: "Franco Lit. Middle East, N. Africa", level: "upper" },
  { code: "GEO505", title: "Regional Analysis of Canada", level: "upper" },
  { code: "GEO507", title: "Explorations of the Urban Environment", level: "upper" },
  { code: "GEO509", title: "Food, Place and Identity", level: "upper" },
  { code: "GEO520", title: "Global Political Geography", level: "upper" },
  { code: "GEO522", title: "Geography of the Middle East", level: "upper" },
  { code: "GEO605", title: "The Geography of the Canadian North", level: "upper" },
  { code: "GEO607", title: "Cities and the Canadian Economic Landscape", level: "upper" },
  { code: "GEO609", title: "cyberspace@geography.ca", level: "upper" },
  { code: "GEO620", title: "Political Geog of Nations and Localities", level: "upper" },
  { code: "GEO702", title: "Technology and the Contemporary Environment", level: "upper" },
  { code: "GEO716", title: "Geographies of Health", level: "upper" },
  { code: "GEO720", title: "The Inner Landscape of Culture", level: "upper" },
  { code: "GEO793", title: "The Geography of Toronto", level: "upper" },
  { code: "GEO802", title: "The Geography of Recreation and Leisure", level: "upper" },
  { code: "GEO811", title: "Global Environmental Issues", level: "upper" },
  { code: "GEO820", title: "The Outer Landscape of Culture", level: "upper" },
  { code: "HAU400", title: "Haudenosaunee Leaders and Writers", level: "upper" },
  { code: "HST501", title: "The American Civil War", level: "upper" },
  { code: "HST503", title: "Crime and Punishment in Modern Canada", level: "upper" },
  { code: "HST504", title: "War to War: World Conflict 1900-45", level: "upper" },
  { code: "HST506", title: "The Ancient Egyptian World", level: "upper" },
  { code: "HST510", title: "The United States after 1945", level: "upper" },
  { code: "HST511", title: "Quebec in Canada: A History", level: "upper" },
  { code: "HST522", title: "The Middle East: 1908 to the Present", level: "upper" },
  { code: "HST523", title: "Colonial South Asia, 1757-1947", level: "upper" },
  { code: "HST526", title: "Women and Gender in U.S. History", level: "upper" },
  { code: "HST527", title: "Toronto: Wilderness to Metropolis", level: "upper" },
  { code: "HST532", title: "Elizabethan England", level: "upper" },
  { code: "HST533", title: "Africa Before 1850", level: "upper" },
  { code: "HST540", title: "Espionage: A Modern History", level: "upper" },
  { code: "HST541", title: "Unknown Canada: Rebels, Rioters, Strikers", level: "upper" },
  { code: "HST555", title: "Late Qing and Republican China, 1839-1949", level: "upper" },
  { code: "HST570", title: "African American History", level: "upper" },
  { code: "HST580", title: "Indigenous History: An Introduction", level: "upper" },
  { code: "HST584", title: "Mediaeval Europe: 400-1400", level: "upper" },
  { code: "HST585", title: "Southeast Asia: War and Peace since 1945", level: "upper" },
  { code: "HST602", title: "Propaganda!", level: "upper" },
  { code: "HST603", title: "The Third Reich", level: "upper" },
  { code: "HST604", title: "The Uneasy Peace: The Cold War, 1945-90", level: "upper" },
  { code: "HST610", title: "The Rise of the American Empire", level: "upper" },
  { code: "HST627", title: "Transgender Histories", level: "upper" },
  { code: "HST632", title: "England in the 17th Century", level: "upper" },
  { code: "HST633", title: "Modern Africa", level: "upper" },
  { code: "HST641", title: "Wine, Women, Warriors, Saviours, Sinners", level: "upper" },
  { code: "HST651", title: "Problems in 20th-Century Eastern Europe", level: "upper" },
  { code: "HST655", title: "People's Republic of China, 1949-Present", level: "upper" },
  { code: "HST657", title: "Culture/Politics of Difference in the U.S.", level: "upper" },
  { code: "HST658", title: "Sex in the City", level: "upper" },
  { code: "HST680", title: "Treaties, Land and Indigenous Governance", level: "upper" },
  { code: "HST701", title: "Scientific Technology and Modern Society", level: "upper" },
  { code: "HST702", title: "The First World War", level: "upper" },
  { code: "HST711", title: "Canada and the United States", level: "upper" },
  { code: "HST712", title: "The American City", level: "upper" },
  { code: "HST777", title: "Medicine from Antiquity to 1500 CE", level: "upper" },
  { code: "HST786", title: "Science and Tech in Middle East History", level: "upper" },
  { code: "HST787", title: "Astronomy vs Astrology", level: "upper" },
  { code: "HST788", title: "Water Use in History", level: "upper" },
  { code: "HST789", title: "British Society since 1939", level: "upper" },
  { code: "HST802", title: "The Second World War", level: "upper" },
  { code: "HST807", title: "The Canadian Revolution: Canada 1968-2000", level: "upper" },
  { code: "HST811", title: "The Holocaust", level: "upper" },
  { code: "INT555", title: "Special Topics in Interdisciplinary Studies", level: "upper" },
  { code: "IRL500", title: "Modern and Contemporary Art, Design", level: "upper" },
  { code: "MTH511", title: "Limitations of Measurement", level: "upper" },
  { code: "MTH599", title: "Foundations of Mathematical Thought", level: "upper" },
  { code: "MUS501", title: "Music of World Cultures", level: "upper" },
  { code: "MUS503", title: "Social Issues in Popular Music", level: "upper" },
  { code: "MUS505", title: "The History of Pop Music", level: "upper" },
  { code: "MUS507", title: "Architecture of Music II", level: "upper" },
  { code: "MUS520", title: "Women in Popular Music", level: "upper" },
  { code: "PCS581", title: "Advanced Topics in Astronomy", level: "upper" },
  { code: "PHL500", title: "Philosophy of the Natural Environment", level: "upper" },
  { code: "PHL501", title: "Oppression and the Critique of Power", level: "upper" },
  { code: "PHL503", title: "Ancient and Modern Ethics", level: "upper" },
  { code: "PHL504", title: "Philosophy of Art", level: "upper" },
  { code: "PHL505", title: "Hegel and Marx", level: "upper" },
  { code: "PHL509", title: "Bioethics", level: "upper" },
  { code: "PHL520", title: "Social and Political Philosophy", level: "upper" },
  { code: "PHL521", title: "Personal Identity East and West", level: "upper" },
  { code: "PHL522", title: "Philosophy and Death", level: "upper" },
  { code: "PHL544", title: "Feminist Philosophy", level: "upper" },
  { code: "PHL550", title: "Knowledge, Truth and Belief", level: "upper" },
  { code: "PHL551", title: "Metaphysics", level: "upper" },
  { code: "PHL552", title: "Philosophy of Natural Science", level: "upper" },
  { code: "PHL561", title: "Philosophy of Social Science", level: "upper" },
  { code: "PHL603", title: "Fundamentals of Ethics", level: "upper" },
  { code: "PHL605", title: "Existentialism", level: "upper" },
  { code: "PHL606", title: "Philosophy of Love and Sex", level: "upper" },
  { code: "PHL611", title: "Philosophy of Mind", level: "upper" },
  { code: "PHL612", title: "Philosophy of Law", level: "upper" },
  { code: "PHL614", title: "Philosophy of Human Rights", level: "upper" },
  { code: "PHL622", title: "Classical Arabic Philosophy", level: "upper" },
  { code: "PHL639", title: "Medieval Philosophy", level: "upper" },
  { code: "PHL648", title: "Philosophy and Literature", level: "upper" },
  { code: "PHL661", title: "Marx, Nietzsche and Freud", level: "upper" },
  { code: "PHL708", title: "Early Modern Philosophy", level: "upper" },
  { code: "PHL709", title: "Religion, Science and Philosophy", level: "upper" },
  { code: "PHL710", title: "Philosophy and Film", level: "upper" },
  { code: "PHL923", title: "Philosophy of Religion II", level: "upper" },
  { code: "POL501", title: "Women, Power and Politics", level: "upper" },
  { code: "POL507", title: "Power, Change and Technology", level: "upper" },
  { code: "POL510", title: "The Politics of Sexual Diversity", level: "upper" },
  { code: "POL511", title: "Well-being and Opportunity in Canada", level: "upper" },
  { code: "POL540", title: "Issues in Third World Politics", level: "upper" },
  { code: "POL588", title: "Neoliberalism and its Alternatives", level: "upper" },
  { code: "POL601", title: "Social Movements and Politics", level: "upper" },
  { code: "POL607", title: "Politics of Technology and Globalization", level: "upper" },
  { code: "POL609", title: "Global Justice", level: "upper" },
  { code: "POL613", title: "International Law for Human Protection", level: "upper" },
  { code: "POL620", title: "Sports and Politics", level: "upper" },
  { code: "POL688", title: "Colonialism and Imperialism", level: "upper" },
  { code: "POL720", title: "Canada in the Continent", level: "upper" },
  { code: "PSY504", title: "Social Psychology", level: "upper" },
  { code: "PSY505", title: "Personality Theory", level: "upper" },
  { code: "PSY604", title: "Issues in Psychology", level: "upper" },
  { code: "PSY606", title: "Abnormal Psychology", level: "upper" },
  { code: "PSY607", title: "Drugs and Human Behaviour", level: "upper" },
  { code: "PSY614", title: "Psychology of Sport", level: "upper" },
  { code: "PSY615", title: "The Psychology of Belief and Skepticism", level: "upper" },
  { code: "PSY620", title: "Psychology of Immigration", level: "upper" },
  { code: "PSY621", title: "Psychology of Human Sexuality", level: "upper" },
  { code: "PSY706", title: "Positive Psychology", level: "upper" },
  { code: "PSY707", title: "Models of Stress and Adaptation", level: "upper" },
  { code: "PSY713", title: "Psychology of Perception", level: "upper" },
  { code: "PSY807", title: "Psychology of Prejudice", level: "upper" },
  { code: "PSY813", title: "Psychology of Art and Creativity", level: "upper" },
  { code: "RMG510", title: "I Shop Therefore I Am", level: "upper" },
  { code: "SEM102", title: "Introduction to Visual Semiotics", level: "upper" },
  { code: "SEM301", title: "Cognitive Semiotics", level: "upper" },
  { code: "SOC501", title: "Making a Living: Sociology of Work", level: "upper" },
  { code: "SOC503", title: "Sociology of Education", level: "upper" },
  { code: "SOC505", title: "Sociology of Sport", level: "upper" },
  { code: "SOC506", title: "Health and Society", level: "upper" },
  { code: "SOC507", title: "Race and Ethnicity in Canadian Society", level: "upper" },
  { code: "SOC601", title: "Control and Resistance at Work", level: "upper" },
  { code: "SOC603", title: "Sociology of Gender", level: "upper" },
  { code: "SOC633", title: "Sex, Gender Identities and Sexualities", level: "upper" },
  { code: "SOC701", title: "Social Change: Canadian Perspectives", level: "upper" },
  { code: "SOC702", title: "Anatomy of Human Conflict", level: "upper" },
  { code: "SOC703", title: "Women, Power and the Global South", level: "upper" },
  { code: "SOC704", title: "Aging, Culture and Society", level: "upper" },
  { code: "SOC705", title: "Law, Justice, and Abolition", level: "upper" },
  { code: "SOC707", title: "Religion, Meaning and Power", level: "upper" },
  { code: "SOC800", title: "Theories of Society", level: "upper" },
  { code: "SOC801", title: "Global Power Relations", level: "upper" },
  { code: "SOC802", title: "Issues in War and Peace", level: "upper" },
  { code: "SOC808", title: "Sociology of Food and Eating", level: "upper" },
  { code: "SOC880", title: "Information Technology and Society", level: "upper" },
  { code: "SOC885", title: "Women, Islam and Modernity", level: "upper" },
  { code: "SOC902", title: "Hollywood and Society", level: "upper" },
  { code: "SPN301", title: "Intermediate Spanish I", level: "upper" },
  { code: "SPN401", title: "Intermediate Spanish II", level: "upper" },
  { code: "SPN501", title: "Advanced Spanish I", level: "upper" },
  { code: "SPN503", title: "Gender and Religion in Early Modern Spain", level: "upper" },
  { code: "SPN507", title: "English-Spanish Translation I", level: "upper" },
  { code: "SPN510", title: "Effective Writing", level: "upper" },
  { code: "SPN601", title: "Advanced Spanish II", level: "upper" },
  { code: "SPN607", title: "English-Spanish Translation II", level: "upper" },
  { code: "SPN610", title: "Spanish Writing Composition", level: "upper" },
  { code: "SPN704", title: "Latin American Culture I", level: "upper" },
  { code: "SPN705", title: "The Boom in Latin American Literature", level: "upper" },
  { code: "SPN707", title: "Spanish-English Translation", level: "upper" },
  { code: "SPN708", title: "Contemporary Spanish Fiction", level: "upper" },
  { code: "SPN710", title: "History of the Spanish Language", level: "upper" },
  { code: "SPN803", title: "Latin American Short Story", level: "upper" },
  { code: "SPN804", title: "Latin American Culture II", level: "upper" },
  { code: "SPN810", title: "Cultural Context of Writing", level: "upper" },
  { code: "SPS502", title: "Spanish Caribbean Literature and Culture", level: "upper" },
  { code: "SPS503", title: "Sex in the Early Modern City", level: "upper" },
  { code: "SSH505", title: "Making the Future", level: "upper" },
  { code: "SWP505", title: "Critical Eq. and Movements of Resistance", level: "upper" },
];

// Build lookup sets from the array
export const LOWER_LIBERALS: Set<string> = new Set(
  LIBERAL_COURSES.filter((c) => c.level === "lower").map((c) => c.code)
);

export const UPPER_LIBERALS: Set<string> = new Set(
  LIBERAL_COURSES.filter((c) => c.level === "upper").map((c) => c.code)
);

export type LiberalCategory = "lower" | "upper" | null;

export function getLiberalCategory(courseCode: string): LiberalCategory {
  if (LOWER_LIBERALS.has(courseCode)) return "lower";
  if (UPPER_LIBERALS.has(courseCode)) return "upper";
  return null;
}

export function getLiberalLabel(category: LiberalCategory): string {
  switch (category) {
    case "lower": return "Lower Liberal";
    case "upper": return "Upper Liberal";
    default: return "";
  }
}

// O(1) title lookup by course code (search filters over all courses per keystroke)
const TITLE_BY_CODE: Map<string, string> = new Map(
  LIBERAL_COURSES.map((c) => [c.code, c.title])
);

export function getLiberalTitle(courseCode: string): string | null {
  return TITLE_BY_CODE.get(courseCode) ?? null;
}